"""
Unit 2.14 -- QueryResult: QueryService's domain-level return type.

Lives in app/schemas (domain layer), NOT app/api (adapter layer) -- the
API layer's request/response DTOs (app/api/v1/schemas.py) are a separate,
deliberately distinct set of types that map to/from this one, per "the
FastAPI layer must remain an API adapter only."
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from app.schemas.retrieval import Decision
from app.schemas.retrieval_domain import VerificationDiagnostics


class QueryResult(BaseModel):
    """
    Business/observability split preserved one level up: `decision`
    (with its attached Explainability, Milestone 1) is what a client acts
    on; `diagnostics` (Unit 2.9) is what a dashboard would show. Neither
    is flattened into the other.

    Unit 3.9 addition: `answer` -- natural language response generated by ResponseGenerator.
    """

    decision: Decision
    diagnostics: VerificationDiagnostics
    retry_count: int = Field(ge=0)
    answer: Optional[str] = None

